/* global supabase, MESS_MANAGER_CONFIG */
'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = n => `৳${Number(n || 0).toLocaleString('en-BD', {maximumFractionDigits: 2})}`;
const today = () => new Date().toISOString().slice(0, 10);
const monthKey = d => (d || today()).slice(0, 7);
const cfg = window.MESS_MANAGER_CONFIG || {};
const configured = /^https:\/\/.+\.supabase\.co$/.test(cfg.supabaseUrl || '') && !String(cfg.supabaseAnonKey).includes('YOUR_');
const client = configured ? supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey, {
  auth: {persistSession: true, autoRefreshToken: true, detectSessionInUrl: true}
}) : null;
let session = null;
let profile = null;
let mess = null;
let db = {members:[], meals:[], bazar:[], deposits:[], utilities:[], schedules:[], settlements:[], logs:[]};
let realtimeChannel = null;
let realtimeRefresh = null;
let state = {page:'dashboard', month:monthKey(), busy:false};
const adminPages = new Set(['activity','settings']);

function notify(message, type='error') {
  document.querySelector('.toast')?.remove();
  document.body.insertAdjacentHTML('beforeend', `<div class="toast ${type}" role="status">${esc(message)}</div>`);
  setTimeout(() => document.querySelector('.toast')?.remove(), 4500);
}
function requireAdmin(){ if(profile?.role !== 'admin'){ notify('Admin access required.'); return false; } return true; }
function memberName(id){ return db.members.find(m => m.id === id)?.name || '-'; }
function activeMembers(){ return db.members.filter(m => m.active); }
function monthFilter(arr, field='date'){ return arr.filter(x => monthKey(x[field]) === state.month); }
function dateRange(){ const [y,m] = state.month.split('-').map(Number); return [`${state.month}-01`, new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)]; }
function friendlyError(error){ console.error(error); return error?.message || 'Something went wrong. Please try again.'; }
async function run(task, success){
  if(state.busy) return;
  state.busy = true;
  try { await task(); if(success) notify(success, 'success'); }
  catch(error){ notify(friendlyError(error)); }
  finally { state.busy = false; }
}
function assertResult(result){ if(result.error) throw result.error; return result.data; }
async function logActivity(action, entityType, entityId=null, metadata={}){
  const result = await client.from('activity_logs').insert({mess_id:profile.mess_id, actor_id:session.user.id, action, entity_type:entityType, entity_id:entityId, metadata:metadata || {}});
  if(result.error) console.warn('Audit log failed', result.error.message);
}

async function loadData(){
  const [start,end] = dateRange();
  const membersResult = await client.from('members').select('*').order('name');
  db.members = assertResult(membersResult);
  const refreshedProfile = db.members.find(member => member.user_id === session.user.id && member.active);
  if(!refreshedProfile) throw new Error('Your account is no longer an active mess member.');
  profile = refreshedProfile;
  const calls = [
    client.from('meals').select('*').gte('meal_date',start).lte('meal_date',end),
    client.from('bazar_entries').select('*, bazar_items(*)').gte('entry_date',start).lte('entry_date',end).order('entry_date',{ascending:false}),
    client.from('deposits').select('*').gte('deposit_date',start).lte('deposit_date',end).order('deposit_date',{ascending:false}),
    client.from('utility_bills').select('*, utility_bill_members(member_id)').gte('bill_date',start).lte('bill_date',end).order('bill_date',{ascending:false}),
    client.from('bazar_schedules').select('*').gte('schedule_date',start).lte('schedule_date',end).order('schedule_date'),
    client.from('monthly_settlements').select('*').eq('month',start)
  ];
  if(profile.role === 'admin') calls.push(client.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(100));
  const results = await Promise.all(calls);
  results.forEach(assertResult);
  db.meals = results[0].data.map(x => ({...x,date:x.meal_date,memberId:x.member_id,on:x.enabled}));
  db.bazar = results[1].data.map(x => ({...x,date:x.entry_date,items:x.bazar_items || []}));
  db.deposits = results[2].data.map(x => ({...x,date:x.deposit_date,memberId:x.member_id}));
  db.utilities = results[3].data.map(x => ({...x,date:x.bill_date,type:x.bill_type,memberIds:x.utility_bill_members.map(y=>y.member_id)}));
  db.schedules = results[4].data.map(x => ({...x,date:x.schedule_date,names:x.assigned_names,done:x.status==='done'}));
  db.settlements = results[5].data;
  db.logs = results[6]?.data || [];
}
async function bootstrap(authSession){
  session = authSession;
  if(!session){ profile=null; mess=null; if(realtimeChannel) client.removeChannel(realtimeChannel); realtimeChannel=null; render(); return; }
  try {
    profile = assertResult(await client.from('members').select('*').eq('user_id',session.user.id).eq('active',true).single());
    mess = assertResult(await client.from('messes').select('*').eq('id',profile.mess_id).single());
    await loadData();
    subscribeRealtime();
    if(profile.role !== 'admin' && adminPages.has(state.page)) state.page='dashboard';
  } catch(error){ profile=null; if(realtimeChannel) client.removeChannel(realtimeChannel); realtimeChannel=null; notify('Your account is not linked to an active mess. Contact an administrator.'); console.error(error); }
  render();
}

function subscribeRealtime(){
  if(realtimeChannel) client.removeChannel(realtimeChannel);
  realtimeChannel = client.channel(`mess:${profile.mess_id}`)
    .on('postgres_changes', {event:'*', schema:'public'}, payload => {
      const shared = new Set(['members','meals','bazar_entries','bazar_items','deposits','utility_bills','utility_bill_members','bazar_schedules','monthly_settlements']);
      if(!shared.has(payload.table)) return;
      clearTimeout(realtimeRefresh);
      realtimeRefresh = setTimeout(()=>bootstrap(session), 150);
    }).subscribe();
}
function nav(){
  const all=[['dashboard','Dashboard'],['members','Members'],['meals','Meal'],['bazar','Bazar'],['deposits','Deposit'],['utilities','Bills'],['schedule','Schedule'],['settlement','Settlement'],['reports','Reports'],['activity','Activity'],['settings','Settings']];
  const allowed = profile.role === 'admin' ? all : all.filter(([k]) => !adminPages.has(k));
  return allowed.map(([k,l])=>`<button class="${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('');
}
async function go(page){ if(adminPages.has(page) && !requireAdmin()) return; state.page=page; render(); }
function pageTitle(){return {dashboard:'Dashboard',members:'Members',meals:'Daily Meal',bazar:'Bazar Management',deposits:'Deposits',utilities:'Utility Bills',schedule:'Bazar Schedule',settlement:'Monthly Settlement',reports:'Reports',activity:'Activity Log',settings:'Settings'}[state.page] || 'Mess Manager';}
function render(){
  if(!configured) return renderSetup();
  if(!session || !profile) return renderLogin();
  const navigation=nav();
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">Mess Manager</div><nav class="nav" aria-label="Main navigation">${navigation}</nav><div class="sidebar-foot"><button class="btn" id="logout">Logout</button></div></aside><main class="main"><header class="topbar"><div><h1>${pageTitle()}</h1><div class="muted">${esc(mess.name)}</div></div><div class="row"><label class="sr-only" for="month">Month</label><input id="month" type="month" value="${state.month}"/><span class="badge">${esc(profile.name)} · ${esc(profile.role)}</span></div></header><div id="content"></div></main><nav class="mobilebar" aria-label="Mobile navigation">${navigation}</nav></div>`;
  document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
  $('#logout').addEventListener('click',()=>client.auth.signOut());
  $('#month').addEventListener('change', async e=>{state.month=e.target.value; await run(async()=>{await loadData(); render();});});
  renderPage();
}
function renderSetup(){ $('#app').innerHTML=`<div class="login"><div class="card"><h1>Connect Supabase</h1><p class="muted">Copy <code>config.example.js</code> to <code>config.js</code>, add your project URL and publishable key, then reload.</p><div class="notice">Never use a service-role key in browser code. Apply the included migration first so Row Level Security is active.</div></div></div>`; }
function renderLogin(){
  $('#app').innerHTML=`<div class="login"><form class="card" id="loginForm"><h1>Mess Manager</h1><p class="muted">Secure Admin & Member sign in</p><div class="field"><label for="email">Email</label><input id="email" type="email" autocomplete="email" required/></div><div class="field gap-top"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" minlength="8" required/></div><button class="btn primary full gap-top" type="submit">Sign in</button><button class="link-button" id="forgot" type="button">Forgot password?</button></form></div>`;
  $('#loginForm').addEventListener('submit', async e=>{e.preventDefault(); await run(async()=>assertResult(await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value})));});
  $('#forgot').addEventListener('click', async()=>{const email=$('#email').value.trim();if(!email)return notify('Enter your email first.');await run(async()=>assertResult(await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname})),'Password reset email sent.');});
}
function renderPage(){ const c=$('#content'); ({dashboard,members,meals,bazar,deposits,utilities,schedule,settlement,reports,activity,settings}[state.page] || dashboard)(c); }
function calcMonth(){
  const members=activeMembers(); const bazarTotal=db.bazar.reduce((s,x)=>s+Number(x.amount),0); const totalUnits=db.meals.filter(x=>x.on).reduce((s,x)=>s+Number(x.units||1),0); const rate=totalUnits?bazarTotal/totalUnits:0;
  return members.map(member=>{const units=db.meals.filter(x=>x.memberId===member.id&&x.on).reduce((s,x)=>s+Number(x.units||1),0);const food=units*rate;const util=db.utilities.reduce((s,u)=>s+(u.memberIds.includes(member.id)?Number(u.amount)/(u.memberIds.length||1):0),0);const deposit=db.deposits.filter(x=>x.memberId===member.id).reduce((s,x)=>s+Number(x.amount),0);return {member,units,food,util,deposit,total:food+util,balance:deposit-food-util};});
}
function dashboard(c){let calc=calcMonth();const bazarTotal=db.bazar.reduce((s,x)=>s+Number(x.amount),0),dep=calc.reduce((s,x)=>s+x.deposit,0),util=db.utilities.reduce((s,x)=>s+Number(x.amount),0),due=calc.reduce((s,x)=>s+Math.max(0,-x.balance),0);c.innerHTML=`<div class="grid kpis"><div class="card kpi"><div class="label">মোট বাজার</div><div class="value">${money(bazarTotal)}</div></div><div class="card kpi"><div class="label">মোট জমা</div><div class="value">${money(dep)}</div></div><div class="card kpi"><div class="label">Utility Bills</div><div class="value">${money(util)}</div></div><div class="card kpi"><div class="label">মোট Due</div><div class="value">${money(due)}</div></div></div><div class="section-head"><h2>Member Summary</h2></div>${settlementTable(calc)}`;}
function members(c){const controls=profile.role==='admin';c.innerHTML=`<div class="section-head"><h2>সব Member</h2>${controls?'<button class="btn primary" data-add>+ Add Member</button>':''}</div>${controls?'<div class="notice">Create an Auth user securely in Supabase, then link its user UUID here. Never share temporary passwords.</div>':''}<div class="list">${db.members.map(m=>`<div class="list-item"><div><b>${esc(m.name)}</b><div class="muted">${m.active?'Active':'Inactive'} · ${esc(m.role)} · ${esc(m.email||'No email')}</div><div class="muted">${esc(m.phone||'No phone')} · Joined ${esc(m.join_date||'-')}</div></div>${controls?`<div class="actions"><button class="btn" data-edit="${m.id}">Edit</button><button class="btn danger" data-toggle="${m.id}">${m.active?'Deactivate':'Activate'}</button></div>`:''}</div>`).join('')}</div>`;if(!controls)return;c.querySelector('[data-add]').onclick=()=>memberModal();c.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>memberModal(x.dataset.edit));c.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=()=>toggleMember(x.dataset.toggle));}
function memberModal(id){const m=db.members.find(x=>x.id===id)||{name:'',email:'',phone:'',join_date:today(),user_id:'',role:'member',active:true};modal(`<h2>${id?'Edit':'Add'} Member</h2><form id="memberForm"><div class="form-grid"><div class="field"><label>Name</label><input name="name" value="${esc(m.name)}" required maxlength="120"/></div><div class="field"><label>Email</label><input name="email" type="email" value="${esc(m.email||'')}"/></div><div class="field"><label>Phone</label><input name="phone" type="tel" value="${esc(m.phone||'')}" maxlength="40"/></div><div class="field"><label>Join date</label><input name="join_date" type="date" value="${esc(m.join_date||today())}" required/></div><div class="field"><label>Auth user UUID (optional)</label><input name="user_id" value="${esc(m.user_id||'')}" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></div><div class="field"><label>Role</label><select name="role"><option value="member">Member</option><option value="admin" ${m.role==='admin'?'selected':''}>Admin</option></select></div></div><div class="actions gap-top"><button class="btn primary">Save</button><button class="btn" type="button" data-close>Cancel</button></div></form>`);$('[data-close]').onclick=closeModal;$('#memberForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload={mess_id:profile.mess_id,name:f.get('name').trim(),email:f.get('email').trim()||null,phone:f.get('phone').trim()||null,join_date:f.get('join_date'),user_id:f.get('user_id').trim()||null,role:f.get('role')};await run(async()=>{const q=id?client.from('members').update(payload).eq('id',id):client.from('members').insert(payload);assertResult(await q);await logActivity(id?'update':'create','member',id,null);closeModal();await loadData();render();},'Member saved.');};}
async function toggleMember(id){await run(async()=>{const m=db.members.find(x=>x.id===id);assertResult(await client.from('members').update({active:!m.active}).eq('id',id));await logActivity('status_change','member',id,{active:!m.active});await loadData();render();},'Member status updated.');}
function meals(c){const [start,end]=dateRange();const dates=[];for(let d=new Date(start+'T00:00:00Z'),last=new Date(end+'T00:00:00Z');d<=last;d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));const visible=activeMembers();c.innerHTML=`<div class="card"><div class="muted">প্রতিদিন meal ON/OFF করুন। Missing days default to OFF and are created securely when toggled.</div></div><div class="section-head"><h2>Daily Meal</h2></div><div class="table-wrap"><table><thead><tr><th>Date</th>${visible.map(m=>`<th>${esc(m.name)}</th>`).join('')}</tr></thead><tbody>${dates.map(date=>`<tr><td>${date}</td>${visible.map(m=>{const x=db.meals.find(z=>z.date===date&&z.memberId===m.id);return `<td><button class="btn ${x?.on?'good':''}" ${profile.role==='admin'?'':'disabled'} data-meal-member="${m.id}" data-meal-date="${date}" data-current="${x?.on?'true':'false'}">${x?.on?'ON':'OFF'}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;c.querySelectorAll('[data-meal-member]').forEach(b=>b.onclick=()=>toggleMeal(b.dataset.mealMember,b.dataset.mealDate,b.dataset.current==='true'));}
async function toggleMeal(memberId,date,current){if(!requireAdmin()) return;await run(async()=>{assertResult(await client.from('meals').upsert({mess_id:profile.mess_id,member_id:memberId,meal_date:date,enabled:!current,units:1},{onConflict:'member_id,meal_date'}));await logActivity('toggle','meal',null,{member_id:memberId,date,enabled:!current});await loadData();render();});}
function bazarItemsTable(items){return `<div class="table-wrap"><table><thead><tr><th>Item</th><th>Category</th><th>Quantity</th><th>Unit</th><th>Unit price</th><th>Total</th></tr></thead><tbody>${items.map(item=>`<tr><td>${esc(item.item_name)}</td><td>${esc(item.category)}</td><td>${esc(item.quantity)}</td><td>${esc(item.unit)}</td><td>${money(item.unit_price)}</td><td>${money(item.total ?? Number(item.quantity)*Number(item.unit_price))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No items</td></tr>'}</tbody></table></div>`;}
function bazar(c){const controls=profile.role==='admin';c.innerHTML=`<div class="section-head"><h2>Detailed Bazar</h2>${controls?'<button class="btn primary" data-add>+ Add Bazar</button>':''}</div><div class="list">${db.bazar.map(entry=>`<article class="card"><div class="section-head"><div><b>${esc(entry.date)} · ${esc(memberName(entry.buyer_member_id))}</b>${entry.note?`<div class="muted">${esc(entry.note)}</div>`:''}</div>${controls?`<div class="actions"><button class="btn" data-edit="${entry.id}">Edit</button><button class="btn danger" data-delete="${entry.id}" data-kind="bazar">Delete</button></div>`:''}</div>${bazarItemsTable(entry.items)}<div class="actions gap-top"><b>Grand total: ${money(entry.amount)}</b></div></article>`).join('')||'<div class="card empty">No bazar entries</div>'}</div>`;if(controls)bindCrud(c,'bazar',bazarModal);}
function bazarItemRow(item={item_name:'',category:'Grocery',quantity:1,unit:'kg',unit_price:''}){return `<div class="bazar-item form-grid"><div class="field"><label>Item</label><input name="item_name" value="${esc(item.item_name)}" required maxlength="160"/></div><div class="field"><label>Category</label><input name="category" list="bazarCategories" value="${esc(item.category||'Other')}" required maxlength="80"/></div><div class="field"><label>Quantity</label><input name="quantity" type="number" min="0.001" step="0.001" value="${esc(item.quantity)}" required/></div><div class="field"><label>Unit</label><input name="unit" value="${esc(item.unit)}" required maxlength="40"/></div><div class="field"><label>Unit price</label><input name="unit_price" type="number" min="0" step="0.01" value="${esc(item.unit_price)}" required/></div><div class="field"><label>Item total</label><b data-item-total>${money(item.total ?? Number(item.quantity||0)*Number(item.unit_price||0))}</b></div><button class="btn danger" type="button" data-remove-item>Remove</button></div>`;}
function bazarModal(id){const x=db.bazar.find(z=>z.id===id)||{date:today(),buyer_member_id:activeMembers()[0]?.id,note:'',items:[{}]};modal(`<h2>${id?'Edit':'Add'} Bazar</h2><form id="bazarForm"><div class="form-grid"><div class="field"><label>Date</label><input name="entry_date" type="date" value="${x.date}" required/></div><div class="field"><label>Buyer</label><select name="buyer_member_id" required>${activeMembers().map(m=>`<option value="${m.id}" ${x.buyer_member_id===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Note (optional)</label><textarea name="note" maxlength="2000">${esc(x.note||'')}</textarea></div></div><datalist id="bazarCategories">${['Grocery','Vegetable','Fish','Meat','Egg','Oil','Spice','Cleaning','Other'].map(category=>`<option value="${category}">`).join('')}</datalist><div id="bazarItems">${(x.items.length?x.items:[{}]).map(bazarItemRow).join('')}</div><div class="actions gap-top"><button class="btn" type="button" id="addBazarItem">+ Item</button><b>Grand total: <span id="bazarTotal">৳0</span></b></div>${modalButtons()}</form>`);const items=$('#bazarItems');const updateTotal=()=>{let grandTotal=0;items.querySelectorAll('.bazar-item').forEach(row=>{const itemTotal=Number(row.querySelector('[name=quantity]').value||0)*Number(row.querySelector('[name=unit_price]').value||0);row.querySelector('[data-item-total]').textContent=money(itemTotal);grandTotal+=itemTotal;});$('#bazarTotal').textContent=money(grandTotal);};const bindRows=()=>items.querySelectorAll('[data-remove-item]').forEach(button=>button.onclick=()=>{if(items.children.length>1)button.closest('.bazar-item').remove();updateTotal();});items.addEventListener('input',updateTotal);$('#addBazarItem').onclick=()=>{items.insertAdjacentHTML('beforeend',bazarItemRow());bindRows();updateTotal();};bindRows();updateTotal();$('[data-close]').onclick=closeModal;$('#bazarForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),rows=[...items.querySelectorAll('.bazar-item')].map(row=>({item_name:row.querySelector('[name=item_name]').value.trim(),category:row.querySelector('[name=category]').value.trim(),quantity:Number(row.querySelector('[name=quantity]').value),unit:row.querySelector('[name=unit]').value.trim(),unit_price:Number(row.querySelector('[name=unit_price]').value)}));await run(async()=>{const entryId=assertResult(await client.rpc('save_bazar_entry',{p_entry_id:id||null,p_entry_date:f.get('entry_date'),p_buyer_member_id:f.get('buyer_member_id'),p_note:f.get('note').trim(),p_items:rows}));await logActivity(id?'update':'create','bazar',entryId);closeModal();await loadData();render();},'Bazar saved.');};}
function deposits(c){const controls=profile.role==='admin';c.innerHTML=`<div class="section-head"><h2>Deposits</h2>${controls?'<button class="btn primary" data-add>+ Add Deposit</button>':''}</div>${entryTable(db.deposits,[['Date','date'],['Member',x=>memberName(x.memberId)],['Amount','amount'],['Note','note']],'deposits',controls)}`;if(controls)bindCrud(c,'deposits',depositModal);}
function depositModal(id){const x=db.deposits.find(z=>z.id===id)||{date:today(),memberId:activeMembers()[0]?.id,amount:'',note:''};modal(`<h2>${id?'Edit':'Add'} Deposit</h2><form id="dataForm"><div class="form-grid"><div class="field"><label>Date</label><input name="deposit_date" type="date" value="${x.date}" required/></div><div class="field"><label>Member</label><select name="member_id">${activeMembers().map(m=>`<option value="${m.id}" ${x.memberId===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0.01" step="0.01" value="${x.amount}" required/></div><div class="field"><label>Note</label><input name="note" maxlength="500" value="${esc(x.note)}"/></div></div>${modalButtons()}</form>`);bindForm(async p=>{p.mess_id=profile.mess_id;p.amount=Number(p.amount);await persist('deposits',id,p,'deposit');});}
function utilities(c){const controls=profile.role==='admin';c.innerHTML=`<div class="section-head"><h2>Utility Bills</h2>${controls?'<button class="btn primary" data-add>+ Add Bill</button>':''}</div>${entryTable(db.utilities,[['Date','date'],['Type','type'],['Amount','amount'],['Shared By',x=>x.memberIds.map(memberName).join(', ')]],'utilities',controls)}`;if(controls)bindCrud(c,'utilities',utilityModal);}
function utilityModal(id){const x=db.utilities.find(z=>z.id===id)||{date:today(),type:'Gas',amount:'',memberIds:activeMembers().map(m=>m.id)};modal(`<h2>${id?'Edit':'Add'} Utility Bill</h2><form id="dataForm"><div class="form-grid"><div class="field"><label>Date</label><input name="bill_date" type="date" value="${x.date}" required/></div><div class="field"><label>Type</label><select name="bill_type">${['Gas','WiFi','Current','Water','Other'].map(t=>`<option ${t===x.type?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" value="${x.amount}" required/></div><fieldset class="field"><legend>Share With</legend>${activeMembers().map(m=>`<label><input type="checkbox" name="memberIds" value="${m.id}" ${x.memberIds.includes(m.id)?'checked':''}/> ${esc(m.name)}</label>`).join('')}</fieldset></div>${modalButtons()}</form>`);$('#dataForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),memberIds=f.getAll('memberIds');if(!memberIds.length)return notify('Select at least one member.');await run(async()=>{const payload={mess_id:profile.mess_id,bill_date:f.get('bill_date'),bill_type:f.get('bill_type'),amount:Number(f.get('amount'))};let billId=id;if(id)assertResult(await client.from('utility_bills').update(payload).eq('id',id));else billId=assertResult(await client.from('utility_bills').insert(payload).select('id').single()).id;assertResult(await client.from('utility_bill_members').delete().eq('utility_bill_id',billId));assertResult(await client.from('utility_bill_members').insert(memberIds.map(member_id=>({utility_bill_id:billId,member_id}))));await logActivity(id?'update':'create','utility_bill',billId);closeModal();await loadData();render();},'Utility bill saved.');};$('[data-close]').onclick=closeModal;}
function schedule(c){const controls=profile.role==='admin';c.innerHTML=`<div class="section-head"><h2>Bazar Schedule</h2>${controls?'<button class="btn primary" data-add>+ Add Schedule</button>':''}</div>${entryTable(db.schedules,[['Date','date'],['Assigned','names'],['Status',x=>x.done?'Done':'Pending']],'schedules',controls)}`;if(controls)bindCrud(c,'schedules',scheduleModal);}
function scheduleModal(id){const x=db.schedules.find(z=>z.id===id)||{date:today(),names:'',done:false};simpleModal(id,'Schedule',[['schedule_date','Date','date',x.date],['assigned_names','Assigned Names','text',x.names],['status','Status','select',x.done?'done':'pending']],async p=>{p.mess_id=profile.mess_id;await persist('bazar_schedules',id,p,'schedule');});}
function settlementTable(calc){return `<div class="table-wrap"><table><thead><tr><th>Member</th><th>Meals</th><th>Deposit</th><th>Food</th><th>Utility</th><th>Total Bill</th><th>Due/Advance</th></tr></thead><tbody>${calc.map(x=>`<tr><td><b>${esc(x.member.name)}</b></td><td>${x.units}</td><td>${money(x.deposit)}</td><td>${money(x.food)}</td><td>${money(x.util)}</td><td>${money(x.total)}</td><td>${x.balance>=0?`<span class="pill advance">Advance ${money(x.balance)}</span>`:`<span class="pill due">Due ${money(-x.balance)}</span>`}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No data</td></tr>'}</tbody></table></div>`;}
function settlement(c){let calc=calcMonth();c.innerHTML=`<div class="card"><b>Calculation:</b> Bazar cost ÷ active meal units = meal rate. Utilities are divided among selected members. Deposit − total bill = advance/due.</div><div class="section-head"><h2>${state.month} Settlement</h2>${profile.role==='admin'?'<button class="btn primary" id="saveSettlement">Save draft</button>':''}</div>${settlementTable(calc)}`;if($('#saveSettlement'))$('#saveSettlement').onclick=()=>saveSettlements(calc);}
async function saveSettlements(calc){await run(async()=>{const rows=calc.map(x=>({mess_id:profile.mess_id,member_id:x.member.id,month:`${state.month}-01`,meal_units:x.units,food_cost:x.food,utility_cost:x.util,deposit_total:x.deposit,balance:x.balance,status:'draft'}));assertResult(await client.from('monthly_settlements').upsert(rows,{onConflict:'mess_id,member_id,month'}));await logActivity('save_draft','monthly_settlement',state.month);await loadData();render();},'Settlement draft saved.');}
function reports(c){const calc=calcMonth(),units=calc.reduce((s,x)=>s+x.units,0),cost=db.bazar.reduce((s,x)=>s+Number(x.amount),0);c.innerHTML=`<div class="grid kpis"><div class="card kpi"><div class="label">Total Meal Units</div><div class="value">${units}</div></div><div class="card kpi"><div class="label">Food Cost / Unit</div><div class="value">${money(units?cost/units:0)}</div></div><div class="card kpi"><div class="label">Bazar Entries</div><div class="value">${db.bazar.length}</div></div><div class="card kpi"><div class="label">Utility Entries</div><div class="value">${db.utilities.length}</div></div></div><div class="section-head"><h2>Settlement Report</h2></div>${settlementTable(calc)}`;}
function activity(c){c.innerHTML=`<div class="section-head"><h2>Recent Activity</h2></div><div class="list">${db.logs.map(x=>`<div class="list-item"><div><b>${esc(x.action)} ${esc(x.entity_type)}</b><div class="muted">${new Date(x.created_at).toLocaleString()} · ${esc(x.entity_id||'')}</div></div></div>`).join('')||'<div class="card empty">No activity yet</div>'}</div>`;}
function settings(c){c.innerHTML=`<div class="card"><form id="settingsForm"><div class="field"><label>Mess Name</label><input name="name" value="${esc(mess.name)}" required maxlength="120"/></div><div class="actions gap-top"><button class="btn primary">Save Settings</button><button class="btn danger" type="button" id="resetPassword">Send password reset</button></div></form></div>`;$('#settingsForm').onsubmit=async e=>{e.preventDefault();await run(async()=>{assertResult(await client.from('messes').update({name:new FormData(e.target).get('name').trim()}).eq('id',mess.id));await logActivity('update','mess',mess.id);mess.name=new FormData(e.target).get('name').trim();render();},'Settings saved.');};$('#resetPassword').onclick=()=>run(async()=>assertResult(await client.auth.resetPasswordForEmail(session.user.email,{redirectTo:location.origin+location.pathname})),'Password reset email sent.');}
function entryTable(rows,columns,kind,controls=profile.role==='admin'){return `<div class="table-wrap"><table><thead><tr>${columns.map(([h])=>`<th>${h}</th>`).join('')}${controls?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(x=>`<tr>${columns.map(([,key])=>{let value=typeof key==='function'?key(x):x[key];if(key==='amount')value=money(value);return `<td>${esc(value||'-')}</td>`;}).join('')}${controls?`<td><div class="actions"><button class="btn" data-edit="${x.id}">Edit</button><button class="btn danger" data-delete="${x.id}" data-kind="${kind}">Delete</button></div></td>`:''}</tr>`).join('')||`<tr><td colspan="${columns.length+(controls?1:0)}" class="empty">No entries</td></tr>`}</tbody></table></div>`;}
function bindCrud(c,kind,open){c.querySelector('[data-add]').onclick=()=>open();c.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>open(x.dataset.edit));c.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>remove(kind,x.dataset.delete));}
const tableMap={bazar:['bazar_entries','bazar'],deposits:['deposits','deposit'],utilities:['utility_bills','utility_bill'],schedules:['bazar_schedules','schedule']};
async function remove(kind,id){if(!requireAdmin()||!confirm('Delete this entry?'))return;await run(async()=>{const [table,entity]=tableMap[kind];assertResult(await client.from(table).delete().eq('id',id));await logActivity('delete',entity,id);await loadData();render();},'Entry deleted.');}
async function persist(table,id,payload,entity){await run(async()=>{const q=id?client.from(table).update(payload).eq('id',id):client.from(table).insert(payload);assertResult(await q);await logActivity(id?'update':'create',entity,id);closeModal();await loadData();render();},`${entity.replace('_',' ')} saved.`);}
function simpleModal(id,title,fields,onSave){modal(`<h2>${id?'Edit':'Add'} ${title}</h2><form id="dataForm"><div class="form-grid">${fields.map(([name,label,type,value])=>`<div class="field"><label>${label}</label>${type==='textarea'?`<textarea name="${name}" required>${esc(value)}</textarea>`:type==='select'?`<select name="${name}"><option value="pending" ${value==='pending'?'selected':''}>Pending</option><option value="done" ${value==='done'?'selected':''}>Done</option></select>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''} required/>`}</div>`).join('')}</div>${modalButtons()}</form>`);bindForm(onSave);}
function bindForm(onSave){$('[data-close]').onclick=closeModal;$('#dataForm').onsubmit=async e=>{e.preventDefault();await onSave(Object.fromEntries(new FormData(e.target)));};}
function modalButtons(){return `<div class="actions gap-top"><button class="btn primary">Save</button><button class="btn" type="button" data-close>Cancel</button></div>`;}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modal" role="dialog" aria-modal="true"><div class="modal">${html}</div></div>`);}
function closeModal(){ $('#modal')?.remove(); }

if(client){client.auth.onAuthStateChange((_event,newSession)=>setTimeout(()=>bootstrap(newSession),0));client.auth.getSession().then(({data})=>bootstrap(data.session));}else render();
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
