/* Deterministic auth transition and visible feedback. */
'use strict';
(()=>{
 const $=s=>document.querySelector(s), sleep=ms=>new Promise(r=>setTimeout(r,ms)); let transitioning=false;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function busy(b,on,label='Working…'){if(!b)return;if(on){b.dataset.old=b.innerHTML;b.disabled=true;b.setAttribute('aria-busy','true');b.innerHTML=`<span class="mm-spin"></span>${esc(label)}`}else{b.disabled=false;b.removeAttribute('aria-busy');if(b.dataset.old)b.innerHTML=b.dataset.old}}
 function screen(title='Loading your mess…',text='Please wait while we prepare your dashboard.'){$('#app').innerHTML=`<main class="mm-auth-wait"><section><span class="mm-big-spin"></span><h2>${esc(title)}</h2><p>${esc(text)}</p><small>Do not close this page.</small></section></main>`}
 async function ready(){let err;for(let i=0;i<15;i++){try{const r=await client.auth.getSession(),s=r.data.session;if(!s)throw Error('Login session তৈরি হয়নি।');session=s;const p=await client.from('members').select('*').eq('user_id',s.user.id).eq('active',true).single();if(p.error)throw p.error;profile=p.data;const m=await client.from('messes').select('*').eq('id',profile.mess_id).single();if(m.error)throw m.error;mess=m.data;await loadData();subscribeRealtime();state.page='dashboard';render();return}catch(e){err=e;await sleep(400)}}throw err||Error('Account load করা যায়নি।')}
 async function finish(b,label,fn){if(transitioning)return;transitioning=true;busy(b,true,label);try{await fn();screen();await ready();notify('Login successful.','success')}catch(e){transitioning=false;busy(b,false);try{renderLogin()}catch{}notify(e?.message||'Something went wrong. Please try again.')}}
 document.addEventListener('click',async e=>{
  const a=e.target.closest('#verifyAdmin');if(a){e.preventDefault();e.stopImmediatePropagation();const s=JSON.parse(sessionStorage.getItem('mm_admin_setup')||'{}'),token=$('#adminCode')?.value.trim()||'';if(!s.email)return notify('আগে OTP পাঠান।');if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');return finish(a,'Verifying…',async()=>{const v=await functionJson('verify-admin-otp',{email:s.email,token});if(!v.token_hash)throw Error('Verification session তৈরি হয়নি।');const d=assertResult(await client.auth.verifyOtp({token_hash:v.token_hash,type:'email'}));session=d?.session||(await client.auth.getSession()).data.session;if(!session)throw Error('Login session তৈরি হয়নি।');const c=await client.rpc('create_admin_workspace',{p_name:s.name,p_mess_name:s.messName,p_email:s.email});if(c.error&&!String(c.error.message||'').includes('already linked'))throw c.error;sessionStorage.removeItem('mm_admin_setup')})}
  const b=e.target.closest('#verifyOtp');if(b){e.preventDefault();e.stopImmediatePropagation();const token=$('#otpCode')?.value.trim()||'',email=($('#otpEmail')?.value||'').trim().toLowerCase();if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');return finish(b,'Verifying…',async()=>{const d=assertResult(await client.auth.verifyOtp({email,token,type:'email'}));session=d?.session||(await client.auth.getSession()).data.session;if(!session)throw Error('Login session তৈরি হয়নি।');const c=await client.rpc('claim_member_by_email');if(c.error&&!String(c.error.message||'').includes('already'))throw c.error})}
 },true);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b.id==='verifyAdmin'||b.id==='verifyOtp')return;b.classList.add('mm-tap');setTimeout(()=>b.classList.remove('mm-tap'),350)},true);
})();