/* Utility sharing cards, reports, notices and mess chat. */
'use strict';
(() => {
  const baseLoadData = loadData;
  window.loadData = async function loadDataPlus(){
    await baseLoadData();
    const [messages, notices] = await Promise.all([
      client.from('mess_messages').select('*').order('created_at',{ascending:true}).limit(200),
      client.from('mess_notices').select('*').order('created_at',{ascending:false}).limit(30)
    ]);
    db.messages = messages.error ? [] : messages.data;
    db.notices = notices.error ? [] : notices.data;
  };

  function splitAmount(u){ return Number(u.amount||0)/(u.memberIds.length||1); }
  function initials(name){ return String(name||'M').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(); }

  window.utilities = function utilitiesPro(c){
    const controls=profile.role==='admin';
    c.innerHTML=`<div class="section-head"><div><span class="eyebrow">Monthly shared costs</span><h2>Utility Bills</h2></div>${controls?'<button class="btn primary" data-add>+ Add Bill</button>':''}</div><div class="utility-list">${db.utilities.map(u=>{const each=splitAmount(u);return `<article class="utility-card"><div class="utility-top"><div class="utility-icon">${u.type==='Gas'?'🔥':u.type==='WiFi'?'⌁':u.type==='Current'?'⚡':'▦'}</div><div class="utility-title"><span>${esc(u.date)}</span><h3>${esc(u.type)}</h3></div><div class="utility-amount"><span>Total</span><b>${money(u.amount)}</b></div></div><div class="split-banner"><div><span>Shared by</span><b>${u.memberIds.length} member${u.memberIds.length===1?'':'s'}</b></div><div><span>Per person</span><b>${money(each)}</b></div></div><div class="member-chip-list">${u.memberIds.map(id=>`<span class="member-chip"><i>${esc(initials(memberName(id)))}</i>${esc(memberName(id))}<b>${money(each)}</b></span>`).join('')}</div>${controls?`<div class="entry-actions"><button class="btn" data-edit="${u.id}">Edit</button><button class="btn danger" data-delete="${u.id}" data-kind="utilities">Delete</button></div>`:''}</article>`;}).join('')||'<div class="card empty">No utility bills</div>'}</div>`;
    if(controls)bindCrud(c,'utilities',utilityModal);
  };

  function reportText(memberCalc){
    return `${mess.name}\nMonthly Statement — ${state.month}\n\nMember: ${memberCalc.member.name}\nMeals: ${memberCalc.units}\nDeposit: ${money(memberCalc.deposit)}\nFood: ${money(memberCalc.food)}\nUtility: ${money(memberCalc.util)}\nTotal bill: ${money(memberCalc.total)}\n${memberCalc.balance>=0?'Advance':'Due'}: ${money(Math.abs(memberCalc.balance))}`;
  }
  function downloadStatement(memberCalc){
    const html=`<!doctype html><meta charset="utf-8"><title>${esc(memberCalc.member.name)} statement</title><style>body{font-family:system-ui;padding:36px;color:#172033}.box{max-width:680px;margin:auto;border:1px solid #dde5ef;border-radius:20px;padding:28px}h1{color:#2457d6}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #edf1f7}.total{font-size:22px;font-weight:800}</style><div class="box"><h1>${esc(mess.name)}</h1><p>Monthly Statement · ${esc(state.month)}</p><h2>${esc(memberCalc.member.name)}</h2>${[['Meals',memberCalc.units],['Deposit',money(memberCalc.deposit)],['Food',money(memberCalc.food)],['Utility',money(memberCalc.util)],['Total bill',money(memberCalc.total)],[memberCalc.balance>=0?'Advance':'Due',money(Math.abs(memberCalc.balance))]].map(([a,b])=>`<div class="row"><span>${a}</span><b>${b}</b></div>`).join('')}<p>Generated by Mess Manager</p></div><script>window.onload=()=>window.print()<\/script>`;
    const w=window.open('','_blank'); if(!w)return notify('Allow pop-ups to generate PDF.'); w.document.write(html);w.document.close();
  }
  async function sendMemberEmail(memberId,subject,message){
    const r=await client.functions.invoke('mess-notify',{body:{member_id:memberId,subject,message}}); if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);return r.data;
  }
  async function saveNotice(memberId,title,body,type='general'){
    assertResult(await client.from('mess_notices').insert({mess_id:profile.mess_id,created_by:profile.id,target_member_id:memberId||null,title,body,notice_type:type}));
  }
  function noticeModal(memberId){
    const m=db.members.find(x=>x.id===memberId);modal(`<div class="modal-title"><div><span class="eyebrow">Payment reminder</span><h2>Send notice</h2></div><button class="icon-btn" data-close>×</button></div><form id="noticeForm"><div class="field"><label>Member</label><input value="${esc(m?.name||'')}" readonly/></div><div class="field gap-top"><label>Message</label><textarea name="message" rows="5" required>আপনার এই মাসের মেসের বকেয়া/জমার হিসাব দেখে প্রয়োজনীয় টাকা জমা দেওয়ার অনুরোধ রইল।</textarea></div><label class="check-row"><input type="checkbox" name="email" ${m?.email?'checked':'disabled'}/> Email-এও পাঠান ${m?.email?`(${esc(m.email)})`:'— email নেই'}</label><div class="actions gap-top"><button class="btn primary">Send notice</button><button class="btn" type="button" data-close2>Cancel</button></div></form>`);$('[data-close]').onclick=closeModal;$('[data-close2]').onclick=closeModal;$('#noticeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),message=f.get('message').trim();await run(async()=>{await saveNotice(memberId,'টাকা জমা দেওয়ার অনুরোধ',message,'deposit');if(f.get('email'))await sendMemberEmail(memberId,`${mess.name}: Deposit reminder`,message);closeModal();await loadData();},'Notice sent.');};
  }

  window.reports = function reportsPro(c){
    const calc=calcMonth();
    c.innerHTML=`<div class="section-head"><div><span class="eyebrow">Statements & reminders</span><h2>Reports</h2></div></div><div class="report-hero"><div><h3>${esc(state.month)} হিসাব</h3><p>প্রতি member-এর complete monthly statement generate করুন, PDF হিসেবে save করুন এবং admin হলে email/notice পাঠান।</p></div><div class="report-total"><span>Total members</span><b>${calc.length}</b></div></div><div class="report-list">${calc.map(x=>`<article class="report-card"><div class="report-person"><div class="avatar">${esc(initials(x.member.name))}</div><div><h3>${esc(x.member.name)}</h3><span>${x.member.email?esc(x.member.email):'Email not added'}</span></div>${x.balance>=0?`<span class="pill advance">Advance ${money(x.balance)}</span>`:`<span class="pill due">Due ${money(-x.balance)}</span>`}</div><div class="report-mini"><span><small>Deposit</small><b>${money(x.deposit)}</b></span><span><small>Total bill</small><b>${money(x.total)}</b></span><span><small>Meals</small><b>${x.units}</b></span></div><div class="report-actions"><button class="btn" data-pdf="${x.member.id}">Generate PDF</button>${profile.role==='admin'?`<button class="btn" data-notice="${x.member.id}">Send notice</button><button class="btn primary" data-email="${x.member.id}" ${x.member.email?'':'disabled'}>Email হিসাব</button>`:''}</div></article>`).join('')}</div>`;
    c.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>downloadStatement(calc.find(x=>x.member.id===b.dataset.pdf)));
    c.querySelectorAll('[data-notice]').forEach(b=>b.onclick=()=>noticeModal(b.dataset.notice));
    c.querySelectorAll('[data-email]').forEach(b=>b.onclick=()=>{const x=calc.find(y=>y.member.id===b.dataset.email);run(()=>sendMemberEmail(x.member.id,`${mess.name}: ${state.month} monthly statement`,reportText(x)),'Statement emailed.');});
  };

  window.chat = async function chatPage(c){
    const messages=db.messages||[];
    c.innerHTML=`<div class="chat-shell"><div class="chat-head"><div><span class="eyebrow">Mess community</span><h2>Chat & খাবার আলোচনা</h2><p>Problem, বাজার, আগামীকালের খাবার—সবাই এখানে share করতে পারবে।</p></div></div>${(db.notices||[]).length?`<div class="notice-strip"><b>Latest notice</b><span>${esc(db.notices[0].title)} — ${esc(db.notices[0].body)}</span></div>`:''}<div class="chat-messages" id="chatMessages">${messages.map(m=>{const mine=m.sender_member_id===profile.id;return `<div class="chat-row ${mine?'mine':''}"><div class="chat-avatar">${esc(initials(memberName(m.sender_member_id)))}</div><div class="chat-bubble"><div><b>${esc(memberName(m.sender_member_id))}</b><time>${new Date(m.created_at).toLocaleString()}</time></div><p>${esc(m.body)}</p></div></div>`;}).join('')||'<div class="chat-empty">এখনও কোনো message নেই। প্রথম message লিখুন।</div>'}</div><form class="chat-compose" id="chatForm"><textarea name="body" rows="1" maxlength="2000" placeholder="Message লিখুন…" required></textarea><button class="btn primary" aria-label="Send">Send</button></form></div>`;
    $('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;
    $('#chatForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),body=f.get('body').trim();if(!body)return;await run(async()=>{assertResult(await client.from('mess_messages').insert({mess_id:profile.mess_id,sender_member_id:profile.id,body}));e.target.reset();await loadData();chatPage(c);});};
  };

  const oldRenderPage=renderPage;
  window.renderPage=function renderPagePlus(){if(state.page==='chat')return chat($('#content'));return oldRenderPage();};

  const oldSubscribe=subscribeRealtime;
  window.subscribeRealtime=function subscribeRealtimePlus(){oldSubscribe();
    if(!realtimeChannel)return;
    // Existing channel handles core tables; chat refresh is also refreshed whenever the page is revisited.
  };
})();
