/* Passwordless auth + self-service admin onboarding for Mess Manager. */
'use strict';
(()=>{
let pendingEmail='';
const originalBootstrap=window.bootstrap;
const shell=body=>`<div class="auth-page"><main class="auth-wrap">${body}</main></div>`;
const hero=()=>`<section class="auth-hero"><div class="auth-house"></div><h1 class="auth-brand-title">Mess <b>Manager</b></h1><p class="auth-tagline">Manage your mess, <b style="color:#0874ed">simply.</b></p><p class="auth-bn">বাজার, মিল, খরচ ও হিসাব—সব এক জায়গায়।</p></section>`;
window.bootstrap=async function(s){if(s?.user){const c=await client.rpc('claim_member_by_email');if(c.error)console.warn(c.error.message)}return originalBootstrap(s)};
function renderWelcome(){
$('#app').innerHTML=shell(`${hero()}<section class="auth-card auth-choice"><div class="auth-choice-icon">♟</div><h2>Create Account for Admin</h2><p>Create your mess workspace and manage members, bazar, meals, expenses and more.</p><div class="auth-actions"><button class="btn primary full auth-main-btn" id="newAdmin">Create Admin Account →</button></div><div class="auth-divider">or</div><div class="auth-member-card auth-choice member"><div class="auth-choice-icon">♟</div><h2>Member Login</h2><p>Login with your email and OTP to access your mess.</p><button class="btn full auth-secondary-btn" id="memberLogin">Login as Member →</button></div></section><section class="auth-features"><div class="auth-feature"><i>🛒</i>Bazar<small>বাজার করুন সহজে</small></div><div class="auth-feature"><i>♨</i>Meals<small>মিল ও মেনু পরিচালনা</small></div><div class="auth-feature"><i>◔</i>Expenses<small>খরচ ও হিসাব সহজভাবে</small></div><div class="auth-feature"><i>▣</i>Chat<small>সবার সাথে যোগাযোগ</small></div></section><div class="auth-safe">🛡 Your data is safe with us<small>100% Secure • Private • Encrypted</small></div><section class="auth-how"><h3>How it Works</h3><div class="auth-steps"><div class="auth-step"><b>1 · Admin Creates Account</b>Create your mess</div><div class="auth-step"><b>2 · Admin Adds Members</b>Add member emails</div><div class="auth-step"><b>3 · Members Login</b>Email + OTP</div><div class="auth-step"><b>4 · Start Using</b>Manage together</div></div></section>`);
$('#newAdmin').onclick=renderAdminSignup;$('#memberLogin').onclick=renderMemberLogin;
}
function renderAdminSignup(){
$('#app').innerHTML=shell(`<section class="auth-card"><button class="auth-back" id="authBack">‹</button><div class="auth-form-head"><div class="auth-form-icon">♟</div><h2>Create Admin Account</h2><p class="muted">Create your mess account and start managing everything.</p></div><form id="adminSignup"><div class="field"><label>Your Name</label><input id="adminName" autocomplete="name" maxlength="120" required placeholder="Enter your full name"></div><div class="field gap-top"><label>Email</label><input id="adminEmail" type="email" autocomplete="email" required placeholder="Enter your email"></div><div class="field gap-top"><label>Mess Name</label><input id="messName" maxlength="160" required placeholder="Enter your mess name"></div><button class="btn primary full gap-top auth-main-btn" type="submit">Send verification OTP →</button></form><div id="adminVerify" class="auth-verify hidden"><div class="field gap-top"><label>8-digit OTP</label><input id="adminCode" inputmode="numeric" autocomplete="one-time-code" maxlength="8" placeholder="Enter 8-digit OTP"></div><button class="btn primary full gap-top auth-main-btn" id="verifyAdmin">Verify & Create Account →</button></div><p class="auth-foot">🛡 You will be the admin of this mess. You can add members later.</p></section>`);
$('#authBack').onclick=renderWelcome;
$('#adminSignup').onsubmit=async e=>{e.preventDefault();const email=$('#adminEmail').value.trim().toLowerCase(),name=$('#adminName').value.trim(),messName=$('#messName').value.trim();if(!name||!messName||!email)return notify('সব তথ্য পূরণ করুন।');pendingEmail=email;sessionStorage.setItem('mm_admin_setup',JSON.stringify({name,messName,email}));await run(async()=>{const r=await client.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(r.error)throw r.error;$('#adminVerify').classList.remove('hidden');$('#adminCode').focus()},'OTP পাঠানো হয়েছে।')};
$('#verifyAdmin').onclick=async()=>{const s=JSON.parse(sessionStorage.getItem('mm_admin_setup')||'{}'),token=$('#adminCode').value.trim();if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');await run(async()=>{const v=assertResult(await client.auth.verifyOtp({email:s.email,token,type:'email'}));const sess=v?.session||(await client.auth.getSession()).data.session;if(!sess)throw new Error('Login session তৈরি হয়নি।');const c=await client.rpc('create_admin_workspace',{p_name:s.name,p_mess_name:s.messName,p_email:s.email});if(c.error&&!String(c.error.message||'').includes('already linked'))throw c.error;sessionStorage.removeItem('mm_admin_setup');location.reload()},'Mess তৈরি হয়েছে।')};
}
function renderMemberLogin(){
$('#app').innerHTML=shell(`<section class="auth-card"><button class="auth-back" id="authBack">‹</button><div class="auth-form-head"><div class="auth-form-icon member">♟</div><h2>Member Login</h2><p class="muted">Enter your email and we will send you an 8-digit OTP.</p></div><form id="otpForm"><div class="field"><label>Email</label><input id="otpEmail" type="email" autocomplete="email" value="${esc(pendingEmail)}" required placeholder="Enter your email"></div><button class="btn primary full gap-top auth-main-btn" id="sendOtp">✈ Send OTP</button></form><div id="memberVerify" class="auth-verify hidden"><div class="field gap-top"><label>OTP Code</label><input id="otpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="8" placeholder="Enter 8-digit OTP"></div><button class="btn primary full gap-top auth-main-btn" id="verifyOtp">🔒 Verify & Login</button></div><p class="auth-foot">Not a member? Contact your admin.</p></section>`);
$('#authBack').onclick=renderWelcome;const email=$('#otpEmail'),code=$('#otpCode'),send=$('#sendOtp');$('#otpForm').onsubmit=async e=>{e.preventDefault();pendingEmail=email.value.trim().toLowerCase();if(!pendingEmail)return notify('Email দিন।');await run(async()=>{const r=await fetch(`${cfg.supabaseUrl}/functions/v1/request-mess-otp`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabaseAnonKey},body:JSON.stringify({email:pendingEmail})});if(!r.ok)throw new Error('OTP পাঠানো যাচ্ছে না।');send.textContent='Resend OTP';$('#memberVerify').classList.remove('hidden');code.focus()},'Member account থাকলে OTP পাঠানো হয়েছে।')};$('#verifyOtp').onclick=async()=>{const token=code.value.trim();if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');await run(async()=>{const d=assertResult(await client.auth.verifyOtp({email:pendingEmail||email.value.trim().toLowerCase(),token,type:'email'}));const sess=d?.session||(await client.auth.getSession()).data.session;if(!sess)throw new Error('Login session তৈরি হয়নি।');const c=await client.rpc('claim_member_by_email');if(c.error&&!String(c.error.message||'').includes('already'))throw c.error;location.reload()})};
}
window.renderLogin=()=>{document.querySelector('.toast')?.remove();renderWelcome()};window.renderAdminSignup=renderAdminSignup;window.renderMemberLogin=renderMemberLogin;if(!session)window.renderLogin();
})();