/* Passwordless auth + self-service admin onboarding for Mess Manager. */
'use strict';
(()=>{
let pendingEmail='';
const originalBootstrap=window.bootstrap;
const shell=body=>`<div class="auth-page"><main class="auth-wrap">${body}</main></div>`;
const adminIcon=()=>`<svg class="auth-svg" viewBox="0 0 64 64" aria-hidden="true"><circle cx="28" cy="20" r="10" fill="currentColor"/><path d="M9 51c0-12 8-20 19-20s19 8 19 20H9Z" fill="currentColor"/><path d="M43 35l4 3 5-7 4 3-8 12-8-7 3-4Z" fill="#fff"/></svg>`;
const memberIcon=()=>`<svg class="auth-svg" viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="19" r="9" fill="currentColor"/><circle cx="16" cy="24" r="7" fill="currentColor" opacity=".8"/><circle cx="48" cy="24" r="7" fill="currentColor" opacity=".8"/><path d="M15 52c1-13 8-20 17-20s16 7 17 20H15Z" fill="currentColor"/><path d="M3 50c1-10 6-16 13-16 3 0 6 1 8 3-5 4-8 8-9 13H3Zm58 0H49c-1-5-4-9-9-13 2-2 5-3 8-3 7 0 12 6 13 16Z" fill="currentColor" opacity=".8"/></svg>`;
const houseIcon=()=>`<svg class="auth-brand-svg" viewBox="0 0 120 100" aria-hidden="true"><path d="M15 48 59 10l46 39M25 43v43h70V43" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><path d="M45 53h31l-3 25H48l-3-25Zm7 0v-7c0-6 4-10 9-10s9 4 9 10v7" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><path d="M85 18c7-7 14-2 9 6-3 4-7 5-11 4 0-4 0-7 2-10Z" fill="#24a64a"/></svg>`;
const hero=()=>`<section class="auth-hero"><div class="auth-house">${houseIcon()}</div><h1 class="auth-brand-title">Mess <b>Manager</b></h1><p class="auth-tagline">Manage your mess, <b>simply.</b></p><p class="auth-bn">বাজার, মিল, খরচ ও হিসাব—সব এক জায়গায়।</p></section>`;
async function functionJson(name,body){const r=await fetch(`${cfg.supabaseUrl}/functions/v1/${name}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabaseAnonKey},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch(_){ }if(!r.ok)throw new Error(d.error||'Request failed.');return d}
window.functionJson=functionJson;
window.bootstrap=async function(s){if(s?.user){const c=await client.rpc('claim_member_by_email');if(c.error)console.warn(c.error.message)}return originalBootstrap(s)};
function renderWelcome(){
$('#app').innerHTML=shell(`${hero()}<section class="auth-card auth-choice"><div class="auth-choice-icon">${adminIcon()}</div><h2>Create Account for Admin</h2><p>Create your mess (workspace) and manage members, bazar, meals, expenses and more.</p><button class="btn primary full auth-main-btn" id="newAdmin">Create Admin Account <span>›</span></button><div class="auth-divider">or</div><div class="auth-member-card auth-choice member"><div class="auth-choice-icon">${memberIcon()}</div><h2>Member Login</h2><p>Login with your email and OTP to access your mess.</p><button class="btn full auth-secondary-btn" id="memberLogin">Login as Member <span>›</span></button></div></section><section class="auth-features"><div class="auth-feature"><i>🛒</i>Bazar<small>বাজার করুন<br>সহজে</small></div><div class="auth-feature"><i>🍲</i>Meals<small>মিল ও মেনু<br>পরিচালনা</small></div><div class="auth-feature"><i>◔</i>Expenses<small>খরচ ও হিসাব<br>সহজভাবে</small></div><div class="auth-feature"><i>💬</i>Chat<small>সবার সাথে<br>যোগাযোগ</small></div></section><div class="auth-safe">🛡️ &nbsp; Your data is safe with us<small>100% Secure • Private • Encrypted</small></div>`);
$('#newAdmin').onclick=renderAdminSignup;$('#memberLogin').onclick=renderMemberLogin;
}
function renderAdminSignup(){
$('#app').innerHTML=shell(`<section class="auth-card auth-form-card"><button class="auth-back" id="authBack">‹</button><div class="auth-form-head"><div class="auth-form-icon">${adminIcon()}</div><h2>Create Admin Account</h2><p class="muted">Create your mess account and<br>start managing everything.</p></div><form id="adminSignup"><div class="field"><label>Your Name</label><input id="adminName" autocomplete="name" maxlength="120" required placeholder="Enter your full name"></div><div class="field gap-top"><label>Email</label><input id="adminEmail" type="email" autocomplete="email" required placeholder="Enter your email"></div><div class="field gap-top"><label>Mess Name</label><input id="messName" maxlength="160" required placeholder="Enter your mess name"></div><button class="btn primary full gap-top auth-main-btn" id="adminSendOtp" type="submit">Send verification OTP <span>›</span></button></form><div id="adminVerify" class="auth-verify hidden"><div class="field gap-top"><label>8-digit OTP</label><input id="adminCode" inputmode="numeric" pattern="[0-9]*" autocomplete="one-time-code" maxlength="8" placeholder="Enter 8-digit OTP"></div><button class="btn primary full gap-top auth-main-btn" id="verifyAdmin">Verify & Create Account <span>›</span></button></div><p class="auth-foot">🛡️ &nbsp; You will be the admin of this mess.<br>You can add members later.</p></section>`);
$('#authBack').onclick=renderWelcome;
$('#adminSignup').onsubmit=async e=>{e.preventDefault();const email=$('#adminEmail').value.trim().toLowerCase(),name=$('#adminName').value.trim(),messName=$('#messName').value.trim(),btn=$('#adminSendOtp');if(!name||!messName||!email)return notify('সব তথ্য পূরণ করুন।');if(btn.disabled)return;pendingEmail=email;sessionStorage.setItem('mm_admin_setup',JSON.stringify({name,messName,email}));const old=btn.innerHTML;btn.disabled=true;btn.setAttribute('aria-busy','true');btn.innerHTML='<span class="mm-spin"></span>Sending OTP…';try{await functionJson('request-admin-otp',{email});$('#adminVerify').classList.remove('hidden');btn.innerHTML='Resend verification OTP <span>›</span>';notify('8-digit OTP ইমেইলে পাঠানো হয়েছে।','success');$('#adminCode').focus()}catch(err){notify(err?.message||'OTP পাঠানো যাচ্ছে না।')}finally{btn.disabled=false;btn.removeAttribute('aria-busy');if(!$('#adminVerify')||$('#adminVerify').classList.contains('hidden'))btn.innerHTML=old}};
$('#verifyAdmin').onclick=async()=>{const s=JSON.parse(sessionStorage.getItem('mm_admin_setup')||'{}'),token=$('#adminCode').value.trim();if(!s.email)return notify('আগে OTP পাঠান।');if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');await run(async()=>{const v=await functionJson('verify-admin-otp',{email:s.email,token});if(!v.token_hash)throw new Error('Verification session তৈরি হয়নি।');const verified=assertResult(await client.auth.verifyOtp({token_hash:v.token_hash,type:'email'}));const sess=verified?.session||(await client.auth.getSession()).data.session;if(!sess)throw new Error('Login session তৈরি হয়নি।');const c=await client.rpc('create_admin_workspace',{p_name:s.name,p_mess_name:s.messName,p_email:s.email});if(c.error&&!String(c.error.message||'').includes('already linked'))throw c.error;sessionStorage.removeItem('mm_admin_setup');location.reload()},'Mess তৈরি হয়েছে।')};
}
function renderMemberLogin(){
$('#app').innerHTML=shell(`<section class="auth-card auth-form-card"><button class="auth-back" id="authBack">‹</button><div class="auth-form-head"><div class="auth-form-icon member">${memberIcon()}</div><h2>Member Login</h2><p class="muted">Enter your email and we will send<br>you an 8-digit OTP.</p></div><form id="otpForm"><div class="field"><label>Email</label><input id="otpEmail" type="email" autocomplete="email" value="${esc(pendingEmail)}" required placeholder="Enter your email"></div><button class="btn primary full gap-top auth-main-btn" id="sendOtp">✈ &nbsp; Send OTP</button></form><div id="memberVerify" class="auth-verify hidden"><div class="field gap-top"><label>OTP Code</label><input id="otpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="8" placeholder="Enter 8-digit OTP"></div><button class="btn primary full gap-top auth-main-btn" id="verifyOtp">🔒 &nbsp; Verify & Login</button></div><p class="auth-foot">Not a member? Contact your admin.</p></section>`);
$('#authBack').onclick=renderWelcome;const email=$('#otpEmail'),code=$('#otpCode'),send=$('#sendOtp');$('#otpForm').onsubmit=async e=>{e.preventDefault();pendingEmail=email.value.trim().toLowerCase();if(!pendingEmail)return notify('Email দিন।');if(send.disabled)return;const old=send.innerHTML;send.disabled=true;send.setAttribute('aria-busy','true');send.innerHTML='<span class="mm-spin"></span>Sending OTP…';try{const r=await fetch(`${cfg.supabaseUrl}/functions/v1/request-mess-otp`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabaseAnonKey},body:JSON.stringify({email:pendingEmail})});if(!r.ok)throw new Error('OTP পাঠানো যাচ্ছে না।');send.innerHTML='Resend OTP';$('#memberVerify').classList.remove('hidden');notify('8-digit OTP ইমেইলে পাঠানো হয়েছে।','success');code.focus()}catch(err){send.innerHTML=old;notify(err?.message||'OTP পাঠানো যাচ্ছে না।')}finally{send.disabled=false;send.removeAttribute('aria-busy')}};$('#verifyOtp').onclick=async()=>{const token=code.value.trim();if(!/^\d{8}$/.test(token))return notify('8-digit OTP দিন।');await run(async()=>{const d=assertResult(await client.auth.verifyOtp({email:pendingEmail||email.value.trim().toLowerCase(),token,type:'email'}));const sess=d?.session||(await client.auth.getSession()).data.session;if(!sess)throw new Error('Login session তৈরি হয়নি।');const c=await client.rpc('claim_member_by_email');if(c.error&&!String(c.error.message||'').includes('already'))throw c.error;location.reload()})};
}
window.renderLogin=()=>{document.querySelector('.toast')?.remove();renderWelcome()};window.renderAdminSignup=renderAdminSignup;window.renderMemberLogin=renderMemberLogin;
})();