/* Final mobile polish overrides. */
'use strict';
(() => {
  const memberById = id => db.members.find(m => m.id === id);
  const initials = name => String(name || 'M').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const avatar = (m, cls='') => m?.avatar_url
    ? `<img class="pro-avatar ${cls}" src="${esc(m.avatar_url)}" alt="${esc(m.name||'Member')}"/>`
    : `<span class="pro-avatar fallback ${cls}">${esc(initials(m?.name))}</span>`;

  window.settlementTable = function settlementTablePolished(calc) {
    const cards = calc.map(x => `<article class="summary-pro-card">
      <div class="summary-pro-head">
        ${avatar(x.member)}
        <div class="summary-person"><b>${esc(x.member.name)}</b><small>${x.units} meal units</small></div>
        ${x.balance >= 0 ? `<span class="pill advance">+${money(x.balance)}</span>` : `<span class="pill due">-${money(-x.balance)}</span>`}
      </div>
      <div class="summary-pro-grid">
        <div><span>Deposit</span><b>${money(x.deposit)}</b></div>
        <div><span>Food</span><b>${money(x.food)}</b></div>
        <div><span>Utility</span><b>${money(x.util)}</b></div>
        <div><span>Total Bill</span><b>${money(x.total)}</b></div>
      </div>
    </article>`).join('');

    const rows = calc.map(x => `<tr><td>${esc(x.member.name)}</td><td>${x.units}</td><td>${money(x.deposit)}</td><td>${money(x.food)}</td><td>${money(x.util)}</td><td>${money(x.total)}</td><td>${x.balance>=0?`<span class="pill advance">Advance ${money(x.balance)}</span>`:`<span class="pill due">Due ${money(-x.balance)}</span>`}</td></tr>`).join('');
    return `<div class="desktop-summary table-wrap"><table><thead><tr><th>Member</th><th>Meals</th><th>Deposit</th><th>Food</th><th>Utility</th><th>Total Bill</th><th>Due/Advance</th></tr></thead><tbody>${rows}</tbody></table></div><div class="mobile-summary summary-pro-list">${cards}</div>`;
  };

  window.reports = function reportsPolished(c) {
    const calc = calcMonth();
    c.innerHTML = `<div class="section-head report-page-head"><div><span class="eyebrow">Monthly accounts</span><h2>${esc(state.month)} হিসাব</h2></div><div class="report-count"><span>Members</span><b>${calc.length}</b></div></div>
      <div class="report-list clean-report-list">${calc.map(x => `<article class="report-card clean-report-card">
        <div class="report-person">
          ${avatar(x.member)}
          <div><h3>${esc(x.member.name)}</h3>${x.member.email?`<span>${esc(x.member.email)}</span>`:''}</div>
          ${x.balance>=0?`<span class="pill advance">Advance ${money(x.balance)}</span>`:`<span class="pill due">Due ${money(-x.balance)}</span>`}
        </div>
        <div class="report-stat-grid">
          <div><span>Deposit</span><b>${money(x.deposit)}</b></div>
          <div><span>Total bill</span><b>${money(x.total)}</b></div>
          <div><span>Meals</span><b>${x.units}</b></div>
        </div>
        <div class="report-actions report-actions-pro">
          <button class="btn" data-pdf="${x.member.id}">PDF</button>
          ${profile.role==='admin'?`<button class="btn" data-notice="${x.member.id}">Notice</button><button class="btn primary" data-email="${x.member.id}" ${x.member.email?'':'disabled'}>Email</button>`:''}
        </div>
      </article>`).join('')}</div>`;

    c.querySelectorAll('[data-pdf]').forEach(b => b.onclick = () => {
      const x = calc.find(y=>y.member.id===b.dataset.pdf);
      const w = window.open('', '_blank');
      if (!w) return notify('Allow pop-ups to generate PDF.');
      w.document.write(`<!doctype html><meta charset="utf-8"><title>${esc(x.member.name)} statement</title><style>body{font-family:system-ui;padding:36px;color:#172033}.box{max-width:680px;margin:auto;border:1px solid #dde5ef;border-radius:20px;padding:28px}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #edf1f7}</style><div class="box"><h1>${esc(mess.name)}</h1><p>${esc(state.month)} Monthly Statement</p><h2>${esc(x.member.name)}</h2>${[['Meals',x.units],['Deposit',money(x.deposit)],['Food',money(x.food)],['Utility',money(x.util)],['Total bill',money(x.total)],[x.balance>=0?'Advance':'Due',money(Math.abs(x.balance))]].map(([a,v])=>`<div class="row"><span>${a}</span><b>${v}</b></div>`).join('')}<p>Generated by Mess Manager</p></div><script>window.onload=()=>window.print()<\/script>`);
      w.document.close();
    });
    c.querySelectorAll('[data-notice]').forEach(b => b.onclick = () => typeof noticeModal === 'function' ? noticeModal(b.dataset.notice) : null);
    c.querySelectorAll('[data-email]').forEach(b => b.onclick = () => {
      const x = calc.find(y=>y.member.id===b.dataset.email);
      const text = `${mess.name}\n${state.month} Monthly Statement\n\nMember: ${x.member.name}\nMeals: ${x.units}\nDeposit: ${money(x.deposit)}\nFood: ${money(x.food)}\nUtility: ${money(x.util)}\nTotal bill: ${money(x.total)}\n${x.balance>=0?'Advance':'Due'}: ${money(Math.abs(x.balance))}`;
      run(()=>sendMemberEmail(x.member.id, `${mess.name}: ${state.month} monthly statement`, text), 'Statement emailed.');
    });
  };

  const oldBazar = window.bazar;
  window.bazar = function bazarPolished(c) {
    oldBazar(c);
    c.querySelectorAll('.bazar-read-row').forEach(row => {
      const left = row.children[0];
      if (left) {
        const name = left.querySelector('b');
        const meta = left.querySelector('span');
        if (name) name.classList.add('bazar-item-name');
        if (meta) meta.classList.add('bazar-item-meta');
      }
    });
  };

  const oldRender = window.render;
  window.render = function renderWithPhotoCleanup() {
    oldRender();
    document.querySelectorAll('.member-summary-head .avatar').forEach(el => {
      const name = el.nextElementSibling?.querySelector('b')?.textContent?.trim();
      const m = db.members.find(x=>x.name===name);
      if (m) el.outerHTML = avatar(m);
    });
  };
})();
