/* Professional admin settings, theme preferences, backup and protected reset. */
'use strict';
(()=>{
  const KEY='mm_settings_v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=value=>localStorage.setItem(KEY,JSON.stringify({...read(),...value}));
  const icon=(name)=>({home:'⌂',moon:'◐',bell:'♢',shield:'◇',download:'⇩',danger:'!',info:'i'}[name]||'•');
  const heroMark=()=>profile?.avatar_url?`<img src="${esc(profile.avatar_url)}" alt="${esc(profile.name||'Member')}" style="width:100%;height:100%;object-fit:cover;border-radius:inherit;display:block">`:icon('home');
  function applyTheme(theme=read().theme||'system'){
    const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);
    document.documentElement.dataset.theme=dark?'dark':'light';
    document.documentElement.style.colorScheme=dark?'dark':'light';
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content',dark?'#091426':'#f7f9ff');
  }
  applyTheme();
  matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((read().theme||'system')==='system')applyTheme('system')});
  if(typeof adminPages!=='undefined'&&adminPages?.delete)adminPages.delete('settings');
  const row=(title,text,control,kind='')=>`<div class="setting-row ${kind}"><div class="setting-copy"><b>${title}</b>${text?`<small>${text}</small>`:''}</div>${control}</div>`;
  const toggle=(key,label)=>`<label class="setting-switch" aria-label="${label}"><input type="checkbox" data-pref="${key}" ${read()[key]!==false?'checked':''}><span></span></label>`;
  const themePicker=theme=>`<section class="settings-card"><header><i>${icon('moon')}</i><div><h3>Appearance</h3><p>Choose how Mess Manager looks on this device</p></div></header><div class="theme-picker" role="radiogroup">${[['light','☀','Light'],['dark','◐','Dark'],['system','◒','System']].map(([v,i,l])=>`<button type="button" data-theme-choice="${v}" class="${theme===v?'selected':''}" role="radio" aria-checked="${theme===v}"><i>${i}</i><b>${l}</b></button>`).join('')}</div></section>`;
  function bindCommonSettings(c){c.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>{write({theme:b.dataset.themeChoice});applyTheme(b.dataset.themeChoice);settingsPage(c)});c.querySelectorAll('[data-pref]').forEach(x=>x.onchange=()=>{write({[x.dataset.pref]:x.checked});notify('Preference saved.','success')});}
  function settingsPage(c){
    const prefs=read(),theme=prefs.theme||'system',email=session?.user?.email||profile?.email||'';
    if(profile?.role!=='admin'){
      c.innerHTML=`<section class="settings-hero"><div class="settings-hero-mark">${heroMark()}</div><div><span>PERSONAL SETTINGS</span><h2>${esc(profile?.name||'Member')}</h2><p>${esc(mess?.name||'Mess Manager')} · Member</p></div><span class="settings-admin-badge">Member</span></section><div class="settings-grid">${themePicker(theme)}<section class="settings-card"><header><i>${icon('bell')}</i><div><h3>Notifications</h3><p>Control reminders on this device</p></div></header>${row('Deposit reminders','Payment reminder এবং due alerts.',toggle('depositAlerts','Deposit reminders'))}${row('Bazar schedule alerts','Assigned Bazar date alerts.',toggle('bazarAlerts','Bazar schedule alerts'))}${row('Monthly statement','Settlement ready হলে notification.',toggle('statementAlerts','Monthly statement alerts'))}</section><section class="settings-card"><header><i>${icon('shield')}</i><div><h3>Account</h3><p>Your signed-in member account</p></div></header>${row('Signed-in account',esc(email),'<span class="settings-verified">✓ Verified</span>')}${row('Role & access','Standard member permissions','<span class="settings-value">Member</span>')}</section></div>`;bindCommonSettings(c);return;
    }
    c.innerHTML=`<section class="settings-hero"><div class="settings-hero-mark">${heroMark()}</div><div><span>MESS WORKSPACE</span><h2>${esc(mess.name)}</h2><p>${activeMembers().length} active members · Managed by ${esc(profile.name)}</p></div><span class="settings-admin-badge">Admin</span></section><div class="settings-grid"><section class="settings-card settings-profile"><header><i>${icon('home')}</i><div><h3>Mess profile</h3><p>Workspace identity and basic information</p></div></header><form id="messProfileForm">${row('Mess name','',`<input class="settings-text" name="mess_name" maxlength="160" value="${esc(mess.name)}" required>`)}<div class="settings-action"><button class="btn primary" type="submit">Save mess name</button></div></form></section>${themePicker(theme)}<section class="settings-card"><header><i>${icon('bell')}</i><div><h3>Notifications</h3><p>Control useful reminders on this device</p></div></header>${row('Deposit reminders','Member payment reminder এবং due alerts.',toggle('depositAlerts','Deposit reminders'))}${row('Bazar schedule alerts','Assigned Bazar date ও pending task alerts.',toggle('bazarAlerts','Bazar schedule alerts'))}${row('Monthly statement','Settlement ready হলে notification.',toggle('statementAlerts','Monthly statement alerts'))}</section><section class="settings-card"><header><i>${icon('shield')}</i><div><h3>Account & security</h3><p>Your signed-in admin account</p></div></header>${row('Admin account',esc(email),'<span class="settings-verified">✓ Verified</span>')}${row('Role & access','Workspace owner permissions','<span class="settings-value">Admin</span>')}</section><section class="settings-card"><header><i>${icon('download')}</i><div><h3>Data backup</h3><p>Keep a readable copy before major changes</p></div></header>${row('Export current workspace','Download an Excel workbook with separate sheets for every section.','<button class="btn settings-inline-btn" id="exportMessData">Download Excel</button>')}</section><section class="settings-card settings-danger"><header><i>${icon('danger')}</i><div><h3>Danger zone</h3><p>Permanent workspace actions</p></div></header>${row('Reset workspace','Deletes all data and every member account. Only the current verified admin and Mess workspace remain.','<button class="btn danger" id="startReset">Reset all data</button>','danger-row')}</section><section class="settings-card settings-about"><header><i>${icon('info')}</i><div><h3>About Mess Manager</h3><p>Secure shared-living management</p></div></header>${row('App version','Latest production release','<span class="settings-value">2026.08</span>')}${row('Data sync','Supabase encrypted cloud sync','<span class="settings-live"><i></i> Live</span>')}</section></div>`;
    bindCommonSettings(c);$('#messProfileForm').onsubmit=async e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('mess_name').trim();if(name.length<2)return notify('Mess name দিন।');const btn=e.submitter,old=btn.textContent;btn.disabled=true;btn.textContent='Saving…';try{assertResult(await client.from('messes').update({name}).eq('id',mess.id));mess={...mess,name};render();notify('Mess name updated.','success')}catch(err){notify(friendlyError(err))}finally{btn.disabled=false;btn.textContent=old}};$('#exportMessData').onclick=exportData;$('#startReset').onclick=openReset;
  }
  document.addEventListener('click',e=>{const trigger=e.target.closest?.('#mobileMore');if(!trigger||profile?.role==='admin')return;setTimeout(()=>{const grid=document.querySelector('#moreSheet .sheet-grid');if(!grid||grid.querySelector('[data-member-settings]'))return;const b=document.createElement('button');b.type='button';b.dataset.memberSettings='1';b.innerHTML=`<span>${icon('moon')}</span><b>Settings</b>`;b.onclick=()=>{document.querySelector('#moreSheet')?.remove();state.page='settings';render();};grid.appendChild(b);},0);},true);
  function exportData(){notify('Excel backup is available to admins.','success')}
  function openReset(){notify('Reset is available to verified admins only.');}
  window.settings=settingsPage;
})();
