/* Premium monthly statement preview with iPhone-safe PDF generation and email attachment. */
'use strict';
(()=>{
  const money2=n=>`৳${Number(n||0).toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const safe=s=>esc(s??'');
  const initials=n=>String(n||'M').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
  const itemAmount=i=>Number(i?.total ?? (Number(i?.quantity||0)*Number(i?.unit_price||0)));
  const isFresh=i=>i?.category==='Vegetable'||i?.category==='কাঁচাবাজার';
  const niceDate=v=>{const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?String(v||''):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});};
  const fileName=x=>`${String(mess.name||'mess').replace(/[^\p{L}\p{N}-]+/gu,'-')}-${String(x.member.name||'member').replace(/[^\p{L}\p{N}-]+/gu,'-')}-${state.month}-statement.pdf`;
  function bazarGroups(){return (db.bazar||[]).map(entry=>{const items=entry.items||[],fresh=items.filter(isFresh),normal=items.filter(i=>!isFresh(i)),lines=normal.map(i=>({name:i.item_name,qty:`${i.quantity||''} ${i.unit||''}`.trim(),amount:itemAmount(i),fresh:false}));if(fresh.length)lines.push({name:'কাঁচাবাজার',qty:fresh.map(i=>`${i.item_name}${i.quantity?` ${i.quantity}${i.unit?` ${i.unit}`:''}`:''}`).join(' · '),amount:fresh.reduce((s,i)=>s+itemAmount(i),0),fresh:true});return{id:entry.id,date:entry.date,buyer:memberName(entry.buyer_member_id),amount:Number(entry.amount||lines.reduce((s,l)=>s+l.amount,0)),lines};}).filter(g=>g.lines.length);}
  function summaryMarkup(x){const balance=x.balance>=0?'Advance':'Due';return `<section class="statement-page statement-summary-page"><header class="statement-cover-head"><div class="statement-kicker">Mess Manager · Monthly Statement</div><h1>${safe(mess.name)}</h1><p>Clear, complete and easy-to-read monthly account statement</p><div class="statement-meta"><span>Period: ${safe(state.month)}</span><span>Generated: ${safe(new Date().toLocaleDateString('en-GB'))}</span></div></header><div class="statement-body"><div class="statement-person"><div class="statement-avatar">${safe(initials(x.member.name))}</div><div><h2>${safe(x.member.name)}</h2><p>${safe(x.member.email||'Email not added')}</p></div><div class="statement-status ${x.balance>=0?'advance':'due'}"><small>${balance}</small><b>${money2(Math.abs(x.balance))}</b></div></div><div class="statement-summary"><div class="statement-metric"><small>Meal units</small><b>${safe(x.units)}</b></div><div class="statement-metric"><small>Deposit</small><b>${money2(x.deposit)}</b></div><div class="statement-metric"><small>Food cost</small><b>${money2(x.food)}</b></div><div class="statement-metric"><small>Utility share</small><b>${money2(x.util)}</b></div><div class="statement-metric total"><small>Total bill</small><b>${money2(x.total)}</b></div><div class="statement-metric balance ${x.balance>=0?'advance':'due'}"><small>${balance}</small><b>${money2(Math.abs(x.balance))}</b></div></div><div class="statement-section-title"><h3>Account Breakdown</h3><span>All amounts in BDT</span></div><div class="statement-breakdown"><div class="statement-breakdown-card"><div><span>Total deposited</span><b>${money2(x.deposit)}</b></div><div><span>Food expense share</span><b>${money2(x.food)}</b></div><div><span>Utility expense share</span><b>${money2(x.util)}</b></div></div><div class="statement-breakdown-card"><div><span>Total payable</span><b>${money2(x.total)}</b></div><div><span>Paid / deposited</span><b>${money2(x.deposit)}</b></div><div><span>Closing ${balance.toLowerCase()}</span><b>${money2(Math.abs(x.balance))}</b></div></div></div><div class="statement-footnote"><span>Generated securely by Mess Manager</span><span>This is a computer-generated statement.</span></div></div></section>`;}
  function bazarMarkup(){const groups=bazarGroups(),total=groups.reduce((s,g)=>s+g.amount,0),count=groups.reduce((s,g)=>s+g.lines.reduce((n,l)=>n+(l.fresh?String(l.qty).split(' · ').length:1),0),0);return `<section class="statement-page statement-bazar-page"><div class="statement-bazar-head"><div class="title"><small>Complete monthly purchase record</small><h2>Bazar List</h2><p>${safe(state.month)} · ${count} items grouped by purchase</p></div><div class="statement-bazar-total"><small>Monthly Bazar Total</small><b>${money2(total)}</b></div></div><div class="statement-bazar-grid">${groups.map(g=>`<article class="statement-bazar-card"><div class="statement-bazar-card-head"><div><strong>${safe(niceDate(g.date))}</strong><span>Buyer · ${safe(g.buyer)}</span></div><b>${money2(g.amount)}</b></div><div class="statement-bazar-lines">${g.lines.map(l=>`<div class="statement-bazar-line ${l.fresh?'statement-fresh':''}"><div class="item"><b>${safe(l.name)}</b><small>${safe(l.qty||'-')}</small></div><div class="amount">${money2(l.amount)}</div></div>`).join('')}</div></article>`).join('')||'<div class="empty">No bazar items for this month.</div>'}</div><div class="statement-bazar-footer"><span>${safe(mess.name)} · ${safe(state.month)}</span><span>Complete Bazar List · ${money2(total)}</span></div></section>`;}
  function paperMarkup(x){return `<div class="statement-paper" data-statement-paper>${summaryMarkup(x)}${bazarMarkup()}</div>`;}
  function toolbarMarkup(x){return `<div class="statement-toolbar"><button type="button" class="statement-back" data-statement-back>← Back</button><div></div><div class="toolbar-actions"><button type="button" class="statement-save" data-statement-save>Save PDF</button>${profile.role==='admin'&&x.member.email?'<button type="button" class="statement-email" data-statement-email>Email PDF</button>':''}</div></div>`;}
  function showToast(message){document.querySelector('.statement-toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="statement-toast">${safe(message)}</div>`);setTimeout(()=>document.querySelector('.statement-toast')?.remove(),2600);}
  function setBusy(button,on,label){if(!button)return;if(on){button.dataset.old=button.textContent;button.disabled=true;button.textContent=label}else{button.disabled=false;button.textContent=button.dataset.old||button.textContent}}
  function closeStatement(){document.querySelector('.statement-view')?.remove();document.body.style.overflow='';}
  function openStatement(x){closeStatement();document.body.style.overflow='hidden';document.body.insertAdjacentHTML('beforeend',`<div class="statement-view" data-statement-view>${toolbarMarkup(x)}<div class="statement-stage">${paperMarkup(x)}</div></div>`);const view=document.querySelector('[data-statement-view]');view.querySelector('[data-statement-back]').onclick=closeStatement;view.querySelector('[data-statement-save]').onclick=e=>savePdf(x,e.currentTarget);view.querySelector('[data-statement-email]')?.addEventListener('click',e=>emailPdf(x,e.currentTarget));}
  async function waitPdfEngine(){if(window.html2canvas&&window.jspdf?.jsPDF)return;for(let i=0;i<50;i++){await new Promise(r=>setTimeout(r,120));if(window.html2canvas&&window.jspdf?.jsPDF)return;}throw new Error('PDF engine load হয়নি। Page refresh করে আবার চেষ্টা করুন।');}
  async function waitFonts(){if(document.fonts?.load){await Promise.allSettled([document.fonts.load('400 18px "Noto Sans Bengali"','বাংলা কাঁচাবাজার মুরগি পেঁয়াজ রসুন আদা লাউ'),document.fonts.load('700 18px "Noto Sans Bengali"','বাংলা কাঁচাবাজার মুরগি পেঁয়াজ রসুন আদা লাউ'),document.fonts.ready]);}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(r,160))));}
  async function getVisiblePaper(x){let view=document.querySelector('[data-statement-view]');if(!view){openStatement(x);view=document.querySelector('[data-statement-view]');}const avatar=view?.querySelector('.statement-avatar');if(avatar&&x.member.avatar_url){avatar.innerHTML=`<img src="${safe(x.member.avatar_url)}" alt="">`;avatar.classList.add('has-photo');}await waitFonts();const paper=view?.querySelector('[data-statement-paper]');if(!paper)throw new Error('Statement view পাওয়া যায়নি।');return{view,paper};}
  async function renderCanvas(el){return window.html2canvas(el,{scale:2,useCORS:true,allowTaint:false,backgroundColor:'#ffffff',foreignObjectRendering:false,logging:false,scrollX:0,scrollY:0,width:794,windowWidth:794});}
  function addSlice(pdf,canvas,y,h,addPage,top){const pageW=794,pageH=1122,slice=document.createElement('canvas');slice.width=canvas.width;slice.height=h;const ctx=slice.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,slice.width,slice.height);ctx.drawImage(canvas,0,y,canvas.width,h,0,0,canvas.width,h);if(addPage)pdf.addPage([pageW,pageH],'portrait');const img=slice.toDataURL('image/jpeg',0.96),drawH=pageW*(h/canvas.width);pdf.addImage(img,'JPEG',0,top,pageW,drawH,undefined,'FAST');}
  function addSectionPages(pdf,canvas,section,isFirst){const pageW=794,pageH=1122,scale=canvas.width/section.getBoundingClientRect().width,isBazar=section.classList.contains('statement-bazar-page');if(!isBazar){addSlice(pdf,canvas,0,canvas.height,!isFirst,0);return;}
    const rect=section.getBoundingClientRect();const safeBreaks=[...section.querySelectorAll('.statement-bazar-card')].map(card=>Math.round((card.getBoundingClientRect().bottom-rect.top)*scale)).filter(v=>v>0&&v<canvas.height);const footer=section.querySelector('.statement-bazar-footer');if(footer)safeBreaks.push(Math.round((footer.getBoundingClientRect().top-rect.top)*scale));safeBreaks.sort((a,b)=>a-b);
    let y=0,pageIndex=0;while(y<canvas.height-4){const top=pageIndex===0?0:42,bottom=pageIndex===0?26:52,capacity=Math.floor((pageH-top-bottom)*(canvas.width/pageW)),remaining=canvas.height-y;let h=Math.min(capacity,remaining);if(remaining>capacity){const target=y+capacity,minCut=y+Math.floor(140*scale);const candidates=safeBreaks.filter(v=>v<=target&&v>=minCut&&v>y+2);if(candidates.length)h=candidates[candidates.length-1]-y;}if(h<=4)h=Math.min(capacity,remaining);addSlice(pdf,canvas,y,h,true,top);y+=h;pageIndex++;}}
  async function generatePdfBlob(x){await waitPdfEngine();const {view,paper}=await getVisiblePaper(x),root=document.documentElement,oldTheme=root.getAttribute('data-theme');root.setAttribute('data-theme','light');view.classList.add('statement-capture');const oldScroll=view.scrollTop;view.scrollTop=0;try{await waitFonts();const sections=[...paper.querySelectorAll('.statement-page')];if(!sections.length)throw new Error('Statement content পাওয়া যায়নি।');const pdf=new window.jspdf.jsPDF({unit:'px',format:[794,1122],orientation:'portrait',hotfixes:['px_scaling'],compress:true});let first=true;for(const section of sections){const canvas=await renderCanvas(section);if(!canvas.width||!canvas.height)throw new Error('PDF page capture failed.');addSectionPages(pdf,canvas,section,first);first=false;}const blob=pdf.output('blob');if(!blob||blob.size<5000)throw new Error('PDF তৈরি হয়নি। আবার চেষ্টা করুন।');return blob;}finally{view.classList.remove('statement-capture');view.scrollTop=oldScroll;if(oldTheme===null)root.removeAttribute('data-theme');else root.setAttribute('data-theme',oldTheme);}}
  async function savePdf(x,button){setBusy(button,true,'Preparing PDF…');try{const blob=await generatePdfBlob(x),name=fileName(x),file=new File([blob],name,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:`${mess.name} monthly statement`});showToast('PDF ready to save.');return;}catch(e){if(e?.name==='AbortError')return;}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.target='_blank';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),120000);showToast('PDF ready.');}catch(e){notify(e?.message||'PDF save failed.');}finally{setBusy(button,false);}}
  function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob);});}
  async function emailPdf(x,button){const old=button?.textContent;setBusy(button,true,'Preparing PDF…');try{const blob=await generatePdfBlob(x),base64=await blobToBase64(blob);if(button)button.textContent='Sending…';const balance=x.balance>=0?'Advance':'Due',message=`Hi ${x.member.name},\n\nYour ${state.month} monthly statement from ${mess.name} is attached as a PDF.\n\nTotal bill: ${money2(x.total)}\n${balance}: ${money2(Math.abs(x.balance))}\n\nOpen the attached PDF for the complete account summary and Bazar list.\n\n- Mess Manager`,html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:28px;color:#10203e"><div style="background:#1760d1;color:white;padding:26px;border-radius:20px"><div style="font-size:12px;opacity:.82;letter-spacing:1px">MESS MANAGER · MONTHLY STATEMENT</div><h1 style="margin:8px 0 4px">${safe(mess.name)}</h1><div>${safe(state.month)}</div></div><h2 style="margin:24px 0 6px">Hi ${safe(x.member.name)},</h2><p style="line-height:1.65;color:#596b86">Your complete monthly statement is attached as a professionally formatted PDF.</p><table role="presentation" style="width:100%;border-collapse:separate;border-spacing:8px"><tr><td style="padding:14px;background:#eef4ff;border-radius:14px"><small style="color:#71809a">Total bill</small><br><b style="font-size:20px">${money2(x.total)}</b></td><td style="padding:14px;background:${x.balance>=0?'#eaf9ef':'#fff0ef'};border-radius:14px"><small style="color:#71809a">${balance}</small><br><b style="font-size:20px">${money2(Math.abs(x.balance))}</b></td></tr></table><p style="color:#8491a5;margin-top:22px">The attached PDF includes the account breakdown and complete Bazar list.</p></div>`;const r=await client.functions.invoke('mess-notify',{body:{member_id:x.member.id,subject:`${mess.name}: ${state.month} monthly statement`,message,html,pdf_base64:base64,pdf_filename:fileName(x)}});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);showToast('PDF emailed successfully.');}catch(e){notify(e?.message||'PDF email failed.');}finally{if(button){button.disabled=false;button.textContent=old||'Email PDF';}}}
  const baseReports=window.reports;window.reports=function statementReports(c){baseReports(c);const calc=calcMonth();c.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>openStatement(calc.find(x=>x.member.id===b.dataset.pdf)));c.querySelectorAll('[data-email]').forEach(b=>b.onclick=()=>{const x=calc.find(y=>y.member.id===b.dataset.email);openStatement(x);setTimeout(()=>document.querySelector('[data-statement-email]')?.click(),300)});};
})();
