-- Secure Web Push support for Mess Chat.
-- Browser clients can only read/delete their own subscriptions. Subscription
-- writes go through security-definer RPCs that derive member/mess identity from
-- auth.uid(), so a client cannot subscribe another member or another mess.
-- VAPID private material is generated by the server and stored in an RLS-locked
-- table that is never readable by anon/authenticated roles.

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  mess_id uuid not null,
  member_id uuid not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint push_subscriptions_member_mess_fk
    foreign key (member_id, mess_id)
    references public.members(id, mess_id)
    on delete cascade
);

create index if not exists push_subscriptions_mess_idx
  on public.push_subscriptions(mess_id);
create index if not exists push_subscriptions_member_idx
  on public.push_subscriptions(member_id);

alter table public.push_subscriptions enable row level security;

revoke all on public.push_subscriptions from anon;
revoke insert, update on public.push_subscriptions from authenticated;
grant select, delete on public.push_subscriptions to authenticated;
grant all on public.push_subscriptions to service_role;

create policy "members read own push subscriptions"
on public.push_subscriptions for select
using (
  exists (
    select 1
    from public.members m
    where m.id = push_subscriptions.member_id
      and m.mess_id = push_subscriptions.mess_id
      and m.user_id = auth.uid()
      and m.active = true
  )
);

create policy "members delete own push subscriptions"
on public.push_subscriptions for delete
using (
  exists (
    select 1
    from public.members m
    where m.id = push_subscriptions.member_id
      and m.mess_id = push_subscriptions.mess_id
      and m.user_id = auth.uid()
      and m.active = true
  )
);

create or replace function public.save_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default ''
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_member_id uuid;
  v_mess_id uuid;
  v_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select m.id, m.mess_id
    into v_member_id, v_mess_id
    from public.members m
   where m.user_id = auth.uid()
     and m.active = true
   limit 1;

  if v_member_id is null then
    raise exception 'Active mess membership required';
  end if;

  p_endpoint := trim(coalesce(p_endpoint, ''));
  p_p256dh := trim(coalesce(p_p256dh, ''));
  p_auth := trim(coalesce(p_auth, ''));
  p_user_agent := left(coalesce(p_user_agent, ''), 1000);

  if p_endpoint !~ '^https://[^[:space:]]+$' or char_length(p_endpoint) > 4000 then
    raise exception 'Invalid push endpoint';
  end if;
  if char_length(p_p256dh) not between 20 and 512 then
    raise exception 'Invalid p256dh key';
  end if;
  if char_length(p_auth) not between 8 and 512 then
    raise exception 'Invalid push auth key';
  end if;

  -- A browser push endpoint represents a device/profile, not an account. If a
  -- different account signs into the same browser later, safely reassign it.
  delete from public.push_subscriptions where endpoint = p_endpoint;

  insert into public.push_subscriptions (
    mess_id, member_id, endpoint, p256dh, auth, user_agent,
    created_at, updated_at, last_seen_at
  ) values (
    v_mess_id, v_member_id, p_endpoint, p_p256dh, p_auth, p_user_agent,
    now(), now(), now()
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.save_push_subscription(text, text, text, text) from public;
revoke all on function public.save_push_subscription(text, text, text, text) from anon;
grant execute on function public.save_push_subscription(text, text, text, text) to authenticated;

create or replace function public.remove_push_subscription(
  p_endpoint text default null
) returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_member_id uuid;
  v_deleted integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select m.id
    into v_member_id
    from public.members m
   where m.user_id = auth.uid()
     and m.active = true
   limit 1;

  if v_member_id is null then
    raise exception 'Active mess membership required';
  end if;

  delete from public.push_subscriptions
   where member_id = v_member_id
     and (p_endpoint is null or endpoint = p_endpoint);
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.remove_push_subscription(text) from public;
revoke all on function public.remove_push_subscription(text) from anon;
grant execute on function public.remove_push_subscription(text) to authenticated;

create table if not exists public.push_vapid_config (
  id boolean primary key default true check (id = true),
  public_key text not null,
  private_key text not null,
  subject text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_vapid_config enable row level security;
revoke all on public.push_vapid_config from anon, authenticated;
grant select, insert, update on public.push_vapid_config to service_role;

comment on table public.push_subscriptions is
  'Per-device Web Push subscriptions for authenticated mess members.';
comment on table public.push_vapid_config is
  'Server-only VAPID signing material. Never expose private_key to browser clients.';
